const data = {
    parqueaderos: [
        {
            "nombre": "EngativaParking",
            "dirección": "calle 68 c # 100 17",
            "slug": "Engativa-calle-68-c-#-100-17",
            "Localidad": "Engativa",
            "precioMinutoMoto": "30 pesos",
            "precioMinutoCarro": "68 pesos",
            "precioTarifaPlenaMoto": "8000 pesos",
            "precioTarifaPlenaCarro": "12 pesos",
            "horario": " L-S 6AM-9PM y D 7AM-6PM",
            "image": "/image/p1.jpg",
            "cuposDisponibles": "Carro 30 y moto 50",
        },
        {
            "nombre": "Ciudad bolivarPK",
            "dirección":  "tv 18 k bis 71 d 61",
            "slug": "Ciudad-bolivar-tv-18-k-bis-71-d-61",
            "Localidad": "Ciudad bolivar ",
            "precioMinutoMoto": "20 pesos",
            "precioMinutoCarro": " 50 pesos",
            "precioTarifaPlenaMoto": "5000 pesos ",
            "precioTarifaPlenaCarro": "10000 pesos",
            "horario": "L-S 6AM-9PM y D 7AM-6PM",
            "image": "/image/p2.jpg",
            "cuposDisponibles": "Carro 15 y motos 20",
        },
        {
            "nombre": "ParkingUSA",
            "dirección": "calle 100 - autopista norte",
            "slug": "Usaquen-calle100-autopista-norte",
            "Localidad": "Usaquen",
            "precioMinutoMoto": " 60 pesos",
            "precioMinutoCarro": " 70 pesos",
            "precioTarifaPlenaMoto": " 9000 pesos",
            "precioTarifaPlenaCarro": "15000 pesos",
            "horario": "L-S 6AM-9PM y D 7AM-6PM",
            "image": "/image/p3.jpg",
            "cuposDisponibles": " carros 100 y motos 200",
        },
        {
            "nombre": "ChapiParking",
            "dirección":  "calle 63 # 7 -42",
            "slug": "Chapinero-calle-63-#-7-42",
            "Localidad": "Chapinero",
            "precioMinutoMoto": " 55 pesos",
            "precioMinutoCarro": "70 pesos",
            "precioTarifaPlenaMoto": "6500 pesos",
            "precioTarifaPlenaCarro": "13000 pesos ",
            "horario": "L-S 6AM-9PM y D 7AM-6PM",
            "image": "/image/p4.jpg",
            "cuposDisponibles": "carros 40 y motos 80",
        },
    ],
};

export default data;